10-17 14:59 Main         INFO     Start
10-17 14:59 Mngr         INFO     Enqued IMCS:0, IRU:0, IREP:0, ISNR:38
10-17 14:59 Mngr         INFO     Enqued IMCS:2, IRU:6, IREP:1, ISNR:42
10-17 14:59 Mngr         INFO     Enqued IMCS:3, IRU:6, IREP:4, ISNR:30
10-17 14:59 Mngr         INFO     Enqued IMCS:4, IRU:6, IREP:0, ISNR:54
10-17 14:59 Mngr         INFO     Enqued IMCS:5, IRU:1, IREP:2, ISNR:50
10-17 14:59 Mngr         INFO     Enqued IMCS:6, IRU:0, IREP:2, ISNR:48
10-17 14:59 Mngr         INFO     Enqued IMCS:7, IRU:1, IREP:5, ISNR:30
10-17 14:59 Mngr         INFO     Enqued IMCS:8, IRU:1, IREP:6, ISNR:60
10-17 15:00 Wrkr06       INFO     Processing IMCS:0, IRU:0, IREP:0, ISNR:38
10-17 15:00 Wrkr07       INFO     Processing IMCS:2, IRU:6, IREP:1, ISNR:42
10-17 15:00 Wrkr03       INFO     Processing IMCS:3, IRU:6, IREP:4, ISNR:30
10-17 15:00 Wrkr01       INFO     Processing IMCS:4, IRU:6, IREP:0, ISNR:54
10-17 15:00 Wrkr05       INFO     Processing IMCS:5, IRU:1, IREP:2, ISNR:50
10-17 15:00 Wrkr04       INFO     Processing IMCS:6, IRU:0, IREP:2, ISNR:48
10-17 15:00 Wrkr00       INFO     Processing IMCS:7, IRU:1, IREP:5, ISNR:30
10-17 15:00 Wrkr02       INFO     Processing IMCS:8, IRU:1, IREP:6, ISNR:60
10-17 15:01 Wrkr06       INFO     Finished IMCS:0, IRU:0, IREP:0, ISNR:38, SNR:-26.2, BLER=1.00000
10-17 15:01 Wrkr06       INFO     Enqued IMCS:0, IRU:0, IREP:0, ISNR:39
10-17 15:01 Wrkr06       INFO     Enqued IMCS:0, IRU:0, IREP:1, ISNR:38
10-17 15:01 Wrkr06       INFO     Processing IMCS:0, IRU:0, IREP:0, ISNR:39
10-17 15:01 Wrkr00       ERROR    The execution of the MATLAB command was interrupted.
Traceback (most recent call last):
  File "stepper.py", line 73, in run
    self._do_work(data)
  File "stepper.py", line 106, in _do_work
    result=self.eng.pysimu(* ( list(data) + [self.MONO,] ))
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/matlabengine.py", line 78, in __call__
    _stderr, feval=True).result()
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/futureresult.py", line 68, in result
    return self.__future.result(timeout)
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
InterruptedError: The execution of the MATLAB command was interrupted.
10-17 15:01 Wrkr05       ERROR    The execution of the MATLAB command was interrupted.
Traceback (most recent call last):
  File "stepper.py", line 73, in run
    self._do_work(data)
  File "stepper.py", line 106, in _do_work
    result=self.eng.pysimu(* ( list(data) + [self.MONO,] ))
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/matlabengine.py", line 78, in __call__
    _stderr, feval=True).result()
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/futureresult.py", line 68, in result
    return self.__future.result(timeout)
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
InterruptedError: The execution of the MATLAB command was interrupted.
10-17 15:01 Wrkr05       INFO     Abort
10-17 15:01 Wrkr02       ERROR    The execution of the MATLAB command was interrupted.
Traceback (most recent call last):
  File "stepper.py", line 73, in run
    self._do_work(data)
  File "stepper.py", line 106, in _do_work
    result=self.eng.pysimu(* ( list(data) + [self.MONO,] ))
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/matlabengine.py", line 78, in __call__
    _stderr, feval=True).result()
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/futureresult.py", line 68, in result
    return self.__future.result(timeout)
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
InterruptedError: The execution of the MATLAB command was interrupted.
10-17 15:01 Wrkr04       ERROR    The execution of the MATLAB command was interrupted.
Traceback (most recent call last):
  File "stepper.py", line 73, in run
    self._do_work(data)
  File "stepper.py", line 106, in _do_work
    result=self.eng.pysimu(* ( list(data) + [self.MONO,] ))
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/matlabengine.py", line 78, in __call__
    _stderr, feval=True).result()
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/futureresult.py", line 68, in result
    return self.__future.result(timeout)
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
InterruptedError: The execution of the MATLAB command was interrupted.
10-17 15:01 Wrkr04       INFO     Abort
10-17 15:01 Wrkr07       ERROR    The execution of the MATLAB command was interrupted.
Traceback (most recent call last):
  File "stepper.py", line 73, in run
    self._do_work(data)
  File "stepper.py", line 106, in _do_work
    result=self.eng.pysimu(* ( list(data) + [self.MONO,] ))
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/matlabengine.py", line 78, in __call__
    _stderr, feval=True).result()
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/futureresult.py", line 68, in result
    return self.__future.result(timeout)
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
InterruptedError: The execution of the MATLAB command was interrupted.
10-17 15:01 Wrkr07       INFO     Abort
10-17 15:01 Wrkr01       ERROR    The execution of the MATLAB command was interrupted.
Traceback (most recent call last):
  File "stepper.py", line 73, in run
    self._do_work(data)
  File "stepper.py", line 106, in _do_work
    result=self.eng.pysimu(* ( list(data) + [self.MONO,] ))
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/matlabengine.py", line 78, in __call__
    _stderr, feval=True).result()
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/futureresult.py", line 68, in result
    return self.__future.result(timeout)
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
InterruptedError: The execution of the MATLAB command was interrupted.
10-17 15:01 Wrkr01       INFO     Abort
10-17 15:01 Wrkr06       ERROR    The execution of the MATLAB command was interrupted.
Traceback (most recent call last):
  File "stepper.py", line 73, in run
    self._do_work(data)
  File "stepper.py", line 106, in _do_work
    result=self.eng.pysimu(* ( list(data) + [self.MONO,] ))
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/matlabengine.py", line 78, in __call__
    _stderr, feval=True).result()
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/futureresult.py", line 68, in result
    return self.__future.result(timeout)
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
InterruptedError: The execution of the MATLAB command was interrupted.
10-17 15:01 Wrkr06       INFO     Abort
10-17 15:01 Wrkr03       ERROR    The execution of the MATLAB command was interrupted.
Traceback (most recent call last):
  File "stepper.py", line 73, in run
    self._do_work(data)
  File "stepper.py", line 106, in _do_work
    result=self.eng.pysimu(* ( list(data) + [self.MONO,] ))
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/matlabengine.py", line 78, in __call__
    _stderr, feval=True).result()
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/futureresult.py", line 68, in result
    return self.__future.result(timeout)
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
InterruptedError: The execution of the MATLAB command was interrupted.
10-17 15:01 Wrkr02       INFO     Abort
10-17 15:01 Wrkr03       INFO     Abort
10-17 15:01 Wrkr00       INFO     Abort
10-17 15:01 Wrkr04       INFO     Closing
10-17 15:01 Wrkr07       INFO     Closing
10-17 15:01 Wrkr01       INFO     Closing
10-17 15:01 Wrkr00       INFO     Closing
10-17 15:01 Wrkr06       INFO     Closing
10-17 15:01 Wrkr05       INFO     Closing
10-17 15:01 Wrkr03       INFO     Closing
10-17 15:01 Wrkr02       INFO     Closing
